__________________________________________________________________________________________________________________
--MANUAL ENTRY FOR ALL USERS
__________________________________________________________________________________________________________________
--STEP1: ENCODE USERS PREDICTIONS
--STEP2: USERS PREDICTIONS ENTRY IN LATESTPREDICTIONS TABLE
__________________________________________________________________________________________________________________
--STEP3: MATCH RESULTS ENTRY IN LATESTPREDICTIONS TABLE
--STEP4: CALCULATE EARNED POINTS AND UPDATE LATESTPREDICTIONS TABLE
__________________________________________________________________________________________________________________
-- ANS TO STEP 3,4 : spPREDICTAUpdatePointsAndResults , [func_Split]
__________________________________________________________________________________________________________________

--STEP:5 UPDATE TOTAL SCORE TABLE,WON/LOSE COLUMN IN SCHEDULE AND TEAMS TABLE,AND DUMP LATESTPREDICTIONS DATA TO USERPREDICTIONS TABLE
__________________________________________________________________________________________________________________



__________________________________________________________________________________________________________________